# General Jekyll Config
highlighter: rouge
url: http://n.khado.me
lsi: false
exclude: [LICENSE, CNAME, README.md, .gitignore]
markdown: kramdown

# Theme customization - please change from the defaults!
themee:
  # Color for top bar, links, etc
  highlight_color: '#3498db'

  # Profile links on the left sidebar, leave blank to ignore
  social:
    github: nguyenkha
    #bitbucket: philipj
    # hacker_news: swanson
    #stackexchange: 348619
    stackoverflow: 1317745
    twitter: donguyenkha
    facebook: nguyenkha
    #tumblr: animalygifs
    linkedin: khado
    #gplus: 110552447039675960964

  # "Hi, I'm _______"
  name: Kha Do
  email: donguyenkha@gmail.com
  tagline: "web developer, blockchain engineer, photographer"

  # Google Analytics key, leave blank to ignore
  google_analytics_key: UA-53247198-1

  # Toggle "Postings are my own" disclaimer in footer
  show_disclaimer: true
