# General Jekyll Config
highlighter: rouge
url: https://kha.do
title: Kha Do
description: Personal website of Kha Do - web engineering, fintech, blockchain, and travel creator stories.
lang: en
timezone: Asia/Ho_Chi_Minh
author:
  name: Kha Do
  email: me@kha.do
logo: /logo.jpg
lsi: false
exclude: [LICENSE, CNAME, README.md, .gitignore]
markdown: kramdown

# Theme customization - please change from the defaults!
themee:
  # Color for top bar, links, etc
  highlight_color: '#3498db'

  # Profile links on the left sidebar, leave blank to ignore
  social:
    github: nguyenkha
    #bitbucket: philipj
    # hacker_news: swanson
    #stackexchange: 348619
    stackoverflow: 1317745
    twitter: donguyenkha
    facebook: nguyenkha
    #tumblr: animalygifs
    linkedin: khado
    #gplus: 110552447039675960964
    youtube: khadilungtung
    tiktok: khadilungtung

  # "Hi, I'm _______"
  name: Kha Do
  email: me@kha.do
  tagline: "#webdeveloper #blockchainengineer #photographer #vlogger"

  # Google Analytics key, leave blank to ignore
  google_analytics_key: UA-53247198-1

  # Toggle "Postings are my own" disclaimer in footer
  show_disclaimer: true

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

twitter:
  username: donguyenkha
  card: summary_large_image

social:
  name: Kha Do
  links:
    - https://github.com/nguyenkha
    - https://www.linkedin.com/in/khado/
    - https://www.youtube.com/@khadilungtung
    - https://www.tiktok.com/@khadilungtung
    - https://x.com/donguyenkha

defaults:
  - scope:
      path: ""
    values:
      image: /logo.jpg
  - scope:
      path: ""
      type: "posts"
    values:
      author: Kha Do
